name: Update README cards

on:
  schedule:
    - cron: "17 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6.0.2

      - name: Generate stats card (light)
        uses: stats-organization/github-readme-stats-action@v2.0.1
        with:
          card: stats
          options: username=${{ github.repository_owner }}&show_icons=true&hide=stars&show=discussions_started,discussions_answered,prs_merged,prs_merged_percentage&include_all_commits=true
          path: profile/stats-light.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          core_version: 2.1.3

      - name: Generate stats card (dark)
        uses: stats-organization/github-readme-stats-action@v2.0.1
        with:
          card: stats
          options: username=${{ github.repository_owner }}&show_icons=true&hide=stars&show=discussions_started,discussions_answered,prs_merged,prs_merged_percentage&include_all_commits=true&theme=dark
          path: profile/stats-dark.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          core_version: 2.1.3

      - name: Generate top languages card (light)
        uses: stats-organization/github-readme-stats-action@v2.0.1
        with:
          card: top-langs
          options: username=${{ github.repository_owner }}&langs_count=4
          path: profile/top-langs-light.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          core_version: 2.1.3

      - name: Generate top languages card (dark)
        uses: stats-organization/github-readme-stats-action@v2.0.1
        with:
          card: top-langs
          options: username=${{ github.repository_owner }}&langs_count=4&theme=dark
          path: profile/top-langs-dark.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          core_version: 2.1.3

      - name: Commit cards
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add profile/*.svg
          git diff --cached --quiet && exit 0
          git commit -m "Update README cards"
          git push
